version: "3.6"
services: 

    fiftyone-db:
        image: mongo
        ports: 
            - 27017:27017
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - ./data:/data/db

    fiftyone:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports: 
            - 5151:5151
        tty: true
        privileged: true
        depends_on: 
            - fiftyone-db
        links: 
            - fiftyone-db
        restart: always

networks: 
    default:
        driver: bridge